# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3203fd0167703b5ff658bd295c8678c7865bc9f404b610630cddeaf5b34a851db382d81213a04186eca235ea9af9e71f5f4f7924154cd8ea8afc60747629acb

test:
  secret_key_base: 42a70f9e8102608d9b8ef699250e04ff78554b0b5b743f852799f29ed079404ce76457516ab257dd36db171b6aca7f3a2315917a6ce2f631041dfccac9c09cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
